### ISSUE TITLE
Failed Compiltaion

### ISSUE THREAD

**Issue by elninho22** [CodeMinion/Printer-Configuration-UI#1]
Please compilation flutter

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\\Users\\CodeMinion\\AndroidstudioProjects\\FlutterProjects\\flutter_printer_setup_sample\\android\\app\\build\\intermediates\\flutter\\debug\\flutter_assets\\AssetManifest.json

Thanks

**Comment by CodeMinion** [comment]
Hi @elninho22 ,

Apologies for that. It seems when I made this sample I tracked everything including the kitchen sink. I have pushed a new version which untracks all those files. If you have a chance please pull the latest and run flutter clean. The errors should not show up anymore.

I'll leave this open so you may confirm that the issue has been resolved. 

Thanks for reaching out!

**Comment by elninho22** [comment]
Show, everything working as expected!

Thanks
